import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import styles from 'src/styles/Home.module.scss';
import classNames from 'classnames/bind';
import Title from '@components/Title';
import Link from 'next/link';
const cx = classNames.bind(styles);

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: { ssg: new Date().toLocaleString() },
    };
};

const Home: NextPage<{ ssg: string }> = ({ ssg }) => {
    return (
        <div className={cx('container')}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={cx('main')}>
                <h1 className={cx('title')}>
                    Welcome to <a href="https://nextjs.org">Next.js</a>
                </h1>
                <h1 className={cx('title')}>Build Time : {ssg}</h1>
                <Title />
                <div style={{ display: 'flex', gap: '10px', color: 'blue' }}>
                    <Link href="/ssr">
                        <h1>SSR</h1>
                    </Link>
                    <Link href="/isr">
                        <h1>ISR</h1>
                    </Link>
                    <Link href="/ssg">
                        <h1>SSG</h1>
                    </Link>
                    <Link href="/csr">
                        <h1>CSR</h1>
                    </Link>
                    <Link href="/csr-with-rest">
                        <h1>CSR with REST</h1>
                    </Link>
                </div>
            </main>
        </div>
    );
};

export default Home;
